# Generated by Django 5.0.6 on 2024-06-29 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('frame', models.CharField(max_length=50)),
                ('speed_gear', models.CharField(max_length=50)),
                ('fork', models.CharField(max_length=50)),
                ('max_load', models.IntegerField()),
                ('motor_voltage', models.FloatField()),
                ('motor_power', models.FloatField()),
                ('motor_type', models.CharField(max_length=50)),
                ('range', models.FloatField()),
                ('display', models.CharField(max_length=50)),
                ('brake', models.CharField(max_length=50)),
                ('battery_voltage', models.FloatField()),
                ('battery_capacity', models.FloatField()),
                ('battery_type', models.CharField(max_length=50)),
                ('tyre_size', models.CharField(max_length=50)),
                ('carton', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
                ('stock', models.IntegerField()),
                ('net_weight', models.FloatField()),
                ('gross_weight', models.FloatField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField(default=0.0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.bikecategory')),
            ],
        ),
        migrations.CreateModel(
            name='BikeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='bike_images/')),
                ('color', models.CharField(max_length=20)),
                ('bike', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bikes.bike')),
            ],
        ),
    ]
