# Generated by Django 5.0.6 on 2024-07-10 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('frame', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='bike_images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='bike_images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='bike_images')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='bike_images')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='bike_images')),
                ('speed_gear', models.CharField(max_length=50)),
                ('fork', models.CharField(max_length=50)),
                ('max_load', models.IntegerField()),
                ('motor_voltage', models.FloatField()),
                ('motor_power', models.FloatField()),
                ('motor_type', models.CharField(max_length=50)),
                ('range', models.IntegerField()),
                ('display', models.CharField(max_length=50)),
                ('brake', models.CharField(max_length=50)),
                ('battery_voltage', models.FloatField()),
                ('battery_capacity', models.FloatField()),
                ('battery_type', models.CharField(max_length=50)),
                ('tyre_size', models.CharField(max_length=50)),
                ('carton', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('stock', models.IntegerField()),
                ('net_weight', models.FloatField()),
                ('gross_weight', models.FloatField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField(default=0.0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='bikes.bikecategory')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
    ]
