# Generated by Django 5.0.6 on 2024-06-29 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikeimages',
            name='bike',
        ),
        migrations.AddField(
            model_name='bike',
            name='images',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bikes.bikeimages'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='range',
            field=models.IntegerField(),
        ),
    ]
