# Generated by Django 5.0.6 on 2024-06-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_remove_bikeimages_bike_bike_images_alter_bike_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='images',
            field=models.FileField(upload_to='bike_images/'),
        ),
    ]
