# Generated by Django 5.0.6 on 2024-06-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_alter_bike_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BikeImages',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='images',
        ),
        migrations.AddField(
            model_name='bike',
            name='image1',
            field=models.ImageField(default='', upload_to='bike_images'),
        ),
        migrations.AddField(
            model_name='bike',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images'),
        ),
        migrations.AddField(
            model_name='bike',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images'),
        ),
        migrations.AddField(
            model_name='bike',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images'),
        ),
        migrations.AddField(
            model_name='bike',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images'),
        ),
    ]
