# Generated by Django 5.0.6 on 2024-07-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_delete_bikeimages_remove_bike_images_bike_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikecategory',
            name='bikes',
            field=models.JSONField(default=list),
        ),
    ]
