# Generated by Django 5.0.6 on 2024-07-01 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_bikecategory_bikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikecategory',
            name='bikes',
        ),
        migrations.AlterField(
            model_name='bike',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='bikes.bikecategory'),
        ),
    ]
