# Generated by Django 5.0.6 on 2024-07-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0006_remove_bikecategory_bikes_alter_bike_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike',
            options={'ordering': ['category']},
        ),
        migrations.AlterModelOptions(
            name='bikecategory',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='bike',
            name='image1',
            field=models.ImageField(upload_to='bike_images'),
        ),
    ]
