# Generated by Django 5.0.6 on 2024-07-05 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cart',
        ),
    ]
