# Generated by Django 5.0.6 on 2024-07-06 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_random'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Random',
        ),
    ]
