# Generated by Django 5.0.6 on 2024-07-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_email_remove_cart_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='first_name',
            field=models.CharField(default='derek', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='last_name',
            field=models.CharField(default='Pesa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='phone',
            field=models.CharField(default='00000000000', max_length=20),
            preserve_default=False,
        ),
    ]
