# Generated by Django 5.0.6 on 2024-07-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_videos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
