# Generated by Django 5.0.6 on 2024-07-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('whatsapp', 'Whatsapp'), ('facebook', 'Facebook'), ('youtube', 'YouTube')], default='phone', max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
