# Generated by Django 5.0.6 on 2024-07-05 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['contact']},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['id']},
        ),
    ]
